// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articke_gist: dynamic(() => import("./ArtickeGist")),
  article: dynamic(() => import("./Article")),
  herp: dynamic(() => import("./Hero")),
  list_key_value: dynamic(() => import("./ListKeyValue")),
};
